/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author realinfo
 */
public class ContactForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContactForm
     */
    public ContactForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        rmale = new javax.swing.JRadioButton();
        rfemale = new javax.swing.JRadioButton();
        txtcontactno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        cmbcity = new javax.swing.JComboBox();
        chkmca = new javax.swing.JCheckBox();
        chkbca = new javax.swing.JCheckBox();
        chkbsc = new javax.swing.JCheckBox();
        btnsave = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setText("Contact Form");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 10, 80, 20);

        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 40, 27, 14);

        jLabel4.setText("Gender");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 70, 35, 14);

        jLabel5.setText("Contact No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 110, 60, 14);

        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 140, 60, 14);

        jLabel7.setText("City");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 190, 19, 14);

        jLabel8.setText("Courses");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 230, 50, 14);
        jPanel1.add(txtname);
        txtname.setBounds(130, 40, 170, 20);

        buttonGroup1.add(rmale);
        rmale.setText("M");
        jPanel1.add(rmale);
        rmale.setBounds(120, 70, 33, 23);

        buttonGroup1.add(rfemale);
        rfemale.setText("F");
        jPanel1.add(rfemale);
        rfemale.setBounds(170, 70, 93, 23);
        jPanel1.add(txtcontactno);
        txtcontactno.setBounds(130, 100, 170, 20);

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 130, 170, 40);

        cmbcity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amritsar", "Batala", "Jalandhar", "Gurdaspur" }));
        jPanel1.add(cmbcity);
        cmbcity.setBounds(130, 190, 75, 20);

        chkmca.setText("MCA");
        jPanel1.add(chkmca);
        chkmca.setBounds(130, 230, 47, 23);

        chkbca.setText("BCA");
        chkbca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbcaActionPerformed(evt);
            }
        });
        jPanel1.add(chkbca);
        chkbca.setBounds(130, 260, 45, 23);

        chkbsc.setText("BSC");
        jPanel1.add(chkbsc);
        chkbsc.setBounds(130, 290, 45, 23);

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave);
        btnsave.setBounds(40, 320, 57, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 330, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkbcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbcaActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       
        String name=txtname.getText();
        String contactno=txtcontactno.getText();
        String gender=""; 
        if(rmale.isSelected())
        {
            
        }
        
        
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkbca;
    private javax.swing.JCheckBox chkbsc;
    private javax.swing.JCheckBox chkmca;
    private javax.swing.JComboBox cmbcity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
